### ISSUE TITLE
passing an invalid reducer to combineReducers() silently fails

### ISSUE THREAD

**Issue by nabn** [reduxjs/redux#1398]
If I pass something to `combineReducers()` that doesn't really return a valid reducer, it silently fails. But if it's the only reducer passed to `combineReducers()`, it throws an error saying valid reducers were not passed. I'm not sure if it's a bug, but sure does look like one to me.

Isn't it better if it warned me if one of the arguments passed to `combineReducers()` wasn't a valid reducer?

I ran into this issue when I forgot to do `export default myReducer` in one of my reducer files.

**Comment by aakashsigdel** [comment]
yes, I think the combineReducer just checks if the object's provided value is a function or not, and doesn't warn if the the function passed is undefined.
```javascript
if (typeof reducers[key] === 'function')  {
  finalReducers[key] = reducers[key];
}
````

When pushing the value to `finalReducer` array, we could make it throw an error or give a warning if the value of the reducer passed is not a function

we could have something like

```javascript
if (typeof reducers[key] === 'function')  {
  finalReducers[key] = reducers[key];
} else {
  throw 'The reducer' + reducers[key] + 'is not a valid type of reducer'
}
```

**Comment by gaearon** [comment]
The reason we have this check is that it used to be a popular pattern to `import * from './reducers'` which will give you an object with some potentially unrelated fields, e.g. `__esModule: true`.

Maybe we should give up on this behavior since we don’t encourage `import *` for reducers anymore but that would be a breaking change.

**Comment by pke** [comment]
Also I might add that a reducer that throws also does so silently. You only see that its supposed to be reduced state is missing in the state.

I had a wrong import for action types and my switch statement then basically said:

```
switch (action.type) {
  case undefined.ACTION_NAME
   ....
}
```

A `sanityError` is saved in combineReducers, though its message does not contain which reducer was insane. That happens because the call to the reducer inside `assertReducerSanity` is not wrapped in `try...catch`

I should be able to make a PR fixing the error reporting.

**Comment by hoangnm** [comment]
Is there any news for this ? I see that it's silently failed because in createStore.js (line 170), we just skip the error. Can we catch the error and log to the console, it helps easier to debug when something wrong...

**Comment by Huanzhang89** [comment]
Agree with @gaearon on this one but maybe in the next major release since this will be a breaking change for a lot of production apps using `import *` for reducers?

**Comment by timdorr** [comment]
@Huanzhang89 Until there's a stable workaround for that case, we're not able to implement it in the library. That should continue to work, as it's a perfectly valid use case and should be expected to work.

**Comment by Huanzhang89** [comment]
@timdorr Okay, thanks for the clarification Tim
