### ISSUE TITLE
Documentation suggestion/discussion: Reusing Reducer Logic

### ISSUE THREAD

**Issue by funwithtriangles** [reduxjs/redux#2520]
I've been thinking about a pattern for reusing reducer logic to that is not suggested here:
http://redux.js.org/docs/recipes/reducers/ReusingReducerLogic.html

I'm wondering about the advantages and disadvantages of it, and if it might be worth mentioning in the documentation on that page.

Instead of "creating" different instances of the same reducer, why not just have a single reducer that has its own slices for each part of your app? Following on from the counter example, the state would look like this:

```javascript
{
   counters: {
     counterA: 0,
     counterB: 1,
     counterC: 0
   }
   ...other state slices here
}
```

And the reducer would look like this:

```javascript
function counterReducer(state, action) => {
  const { name } = action

  switch (action.type) {
    case 'INCREMENT':
        return {
           ...state,
           state[name]: state + 1;
         }
    case 'DECREMENT':
        return {
           ...state,
           state[name]: state - 1;
         }
    default:
      return state
  }
}
```

Does this not achieve the same results but with less complexity? Are there some serious pitfalls that I have not considered? This approach would also allow you to write a single selector function to get the counter value, as you can be more sure about the shape of your state across the app:

```javascript
const getCounterValue = (state, name) => state.counters[name]
```

CC @markerikson @timse (contributors to the page in docs)

**Comment by markerikson** [comment]
There's certainly other patterns I didn't talk about when I wrote that section.  

Two thoughts on your particular example.  First, the snippet you have there won't work right, because `state` is the object, and `state[name]` is the actual value, so `state + 1` isn't correct.  You'd want `state[name]: state[name] + 1` instead.

Second, one pattern that's probably worth discussing is one that Dan shows off in his videos, but I'm not sure if we actually have examples in the docs.  It doesn't have a name yet, but for now let's call it the "single/multiple" pattern.  (Horrible name, but we could come up with something better later.)  This is the idea of having one reducer function that knows how to handle all cases for updating a single item, and then calling that single-item reducer from a parent reducer that tracks many items in an array or an object.  Example:

```js
function counterReducer(state, action) {
    switch(action.type) {
        case "INCREMENT" : return state + 1;
        case "DECREMENT" : return state - 1;
    }
}

function countersArrayReducer(state, action) {
    switch(action.type) {
        case "INCREMENT":
        case "DECREMENT":
            return state.map( (counter, index) => {
                if(index !== action.index) return counter;
                return counterReducer(counter, action);
            });
        default:
            return state;
    }
}

function countersMapReducer(state, action) {
    switch(action.type) {
        case "INCREMENT":
        case "DECREMENT":
            return {
                ...state,
                state[name] : counterReducer(state[name], action
            };
        default:
            return state;
    }
}
```

This would be a good thing to add to the docs, and if you'd like to work on a PR for adding a section on this to the "Reusing Reducer Logic" page, I'd be happy to work with you on getting that in.

**Comment by markerikson** [comment]
Update: per https://twitter.com/acemarke/status/916726020186824705 , we ought to call this approach the "collection / item reducer" pattern.
