### ISSUE TITLE
Add documentation for setting up a redux store with create-react-app

### ISSUE THREAD

**Issue by SeanPlusPlus** [reduxjs/redux#2587]
per this thread:

https://twitter.com/acemarke/status/901929091879841792

**Comment by markerikson** [comment]
Great, thanks for offering to help out.

To recap: skimming through the docs, we have the specific API section for `createStore`, and samples of using `createStore` in our actual example projects, but I don't immediately see good examples of how to go about _using_ `createStore` in a typical application.  I'd like to see a recipe page that covers how to write your own `configureStore` function to encapsulate store creation, and lays out a good sequence of steps that users could adapt to fit their own needs.

In particular, I'd like to use the code and approach from my own [Practical Redux, Part 3: Project Setup](http://blog.isquaredsoftware.com/2016/11/practical-redux-part-3-project-planning-and-setup/) post as a starting point and example.

The recipe _should_ be widely applicable to just about any Redux app, not just CRA, since there CRA itself doesn't care about Redux - it just provides a skeleton React app as a starting point.  However, it may be useful to use CRA as an example of where to call `configureStore()` and use the store in a React app.

**Comment by markerikson** [comment]
It would also be good to first review the docs to see what examples of `createStore` we _do_ have, just in case I'm not thinking of something :)

**Comment by AuroreM** [comment]
Hi @markerikson, 
I'm interesting to work on this, do you know if this issue is still "available" ?

**Comment by timdorr** [comment]
Until they're closed, they're always available to be worked on.

**Comment by markerikson** [comment]
Fixed via #3039 .  Thanks!
