### ISSUE TITLE
Table of contents links are not navigable

### ISSUE THREAD

**Issue by pushpinder107** [reduxjs/redux#3009]
**Do you want to request a *feature* or report a *bug*?**  
Bug.

**What is the current behavior?**

Navigate to any topic in the far section, e.g. https://redux.js.org/faq/general , click on any of the links that appear in the table of contents. The URL changes but the page does not scroll to the correct place.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Attached gif.
![redux](https://user-images.githubusercontent.com/9403361/40653042-955c4b00-6357-11e8-82d0-5a2c0fedabc8.gif)

**What is the expected behavior?**

The page should scroll to the correct place in the page on clicking a link in the table of contents.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Tried Firefox, safari and chrome on macOS Sierra 10.12.6.

**Comment by timdorr** [comment]
The anchor links need to be updated. Can you submit a PR?

**Comment by markerikson** [comment]
This is something I'd pointed out previously in the other docs update thread.  @SamyPesse had said they aren't correctly handling inline anchor tags.

I'd really like to get that working again, because it's nicer to paste in https://redux.js.org/faq/actions#actions-side-effects than it is https://redux.js.org/faq/actions#how-can-i-represent-side-effects-such-as-ajax-calls-why-do-we-need-things-like-action-creators-thunks-and-middleware-to-do-async-behavior .
