### ISSUE TITLE
combineReducer should give warning if a reducer is not a function

### ISSUE THREAD

**Issue by baibhavx** [reduxjs/redux#3027]
*Do you want to request a *feature* or report a *bug*?**  
- Feature 

**What is the current behavior?**  
- If the object supplied to combineReducer has a key whose value is not a function, it simply ignores it.  

``` js
const rootReducer = combineReducers({ 
  todos: todosReducer, 
  steps: {} // no warning, this is simply ignored 
})
```

**What is the expected behavior?**
- It should give a warning, letting the user know that each key should point to a reducer function. 

Please check out this pull-request with proposed changes: https://github.com/reduxjs/redux/pull/3026 

I will be more than happy to write a test case for this feature.

**Comment by timdorr** [comment]
I actually found the reason we can't do that: #124

Unfortunately, because of how Babel can transpile modules, you easily end up with extraneous properties going into your export object (e.g., `import * as Reducers from './reducers'` will have an `_esModule` property). While not a problem by the specification, it's a practical issue users will run into. 

We had the exact same issue with #2279 and had to back out those changes too. Unfortunately, this is still something we need to handle.
