### ISSUE TITLE
RFC: In combineReducers, provide option to add result of sub-reducers to original state object

### ISSUE THREAD

**Issue by johnnyodonnell** [reduxjs/redux#3050]
I found a situation where I would like the result of my sub-reducers to be written to the original state object, rather than a new state object. In combineReducers, the result of the sub-reducers is written to a new state object called `nextState`. If I worked on a pull-request to add this option, is this something you guys would be interested in? Or am I using Redux in a way that wasn't intended?

**Comment by markerikson** [comment]
If I'm interpreting your statement correctly - no, that's absolutely _not_ how Redux is supposed to be used.  Reducers are intended to be pure with no side effects, and that specifically includes mutating the original state values.

Can you show an example of what your code is actually doing, and clarify your use case for why you're doing that?

**Comment by johnnyodonnell** [comment]
Yes, here is my situation: https://stackoverflow.com/questions/51164269/redux-update-one-item-in-a-list-without-updating-all-other-components-that-depe

I have a user object with a list of items. If I update an item, I want only the components that rely on that item to re-render. Instead, any component that relies on the user object also re-renders.

I understand that reducers is supposed to be pure with no side effects, but I'm not seeing an obvious way around this.

**Comment by markerikson** [comment]
Mutating state is _not_ the right answer here :)

First, there's nothing wrong with a React component re-rendering - that's how React works in the first place.  If a component re-renders with the same data and produces the same render output, then React just doesn't update the DOM.  Now, sure, that's considered a "wasted" re-render that probably could have been avoided, but it's only a problem if you're trying to seriously optimize performance.

Second: yes, if you're correctly immutably updating your state, then an update to `state.user.items[3]` should result in new references for `items`, `user`, and `state`, and passing `user` as a prop to the component like that _would_ cause it to re-render.  However, in your specific example, that component is only using `user.name`.  so there's no reason to pass the entire `user` object as a prop - try passing just `name : state.user.name` instead.

Third, you could split up the storage of the user attributes and their associated items into separate parts of the state, so that an update to an item doesn't cause an update to the associated user object.  See the [Normalizing State Shape](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape) page in the docs as an example.

Finally, you could always implement a custom `shouldComponentUpdate` in your component, and do an additional check there to see if the component should skip re-rendering.

Overall, I think you're worrying about this too much.  I do appreciate the offer of a PR, but mutating state is effectively never the right approach with Redux, and not something we would want as part of our baseline.

**Comment by johnnyodonnell** [comment]
That makes sense. A lot of good potential solutions you presented here to check out. Thanks Mark!

**Comment by markerikson** [comment]
Sure, glad that helped clear things up.
