### ISSUE TITLE
Incorrect reference in docs

### ISSUE THREAD

**Issue by jalik** [reduxjs/redux#3175]
**bug**  

On this page: https://redux.js.org/basics/usagewithreact#index-js
The following import is referencing a file that is not in the doc.

```js
import todoApp from './reducers'
```

**Comment by markerikson** [comment]
Hi.  Appreciate the report, but it's not specifically a problem.  The point of that page is to illustrate setting up the React-Redux side of things, not focus on how to write a reducer for a todo app, or work with the actions.  The `<AddTodo>` component file also references a "nonexistent" file when it does `import {addTodo} from "../actions"`.  That's okay, because it's not trying to show a complete reproduceable example in that one page.
