### ISSUE TITLE
ReferenceError: Cannot access 'state' before initialization

### ISSUE THREAD

**Issue by marcosroot** [reduxjs/redux#3492]
That seems to make no sense to me. I try to use state and store in another file, but I always get this error, but when it's done in the same file, it doesn't raise any errors.

obs: i'm using ` redux-starter-kit`

the code:

```
const createStore = () => {
	const store = configureStore({
		reducer,
		middleware,
		devTools: process.env.NODE_ENV !== "production",
	});

	sagaMiddleware.run(saga);

	store.subscribe(() => {
		saveState(toLocalStorage(store.getState()));
	});

	return store;
};

const store = createStore();
export default store;
```

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.

**Comment by marcosroot** [comment]
It's not about use, the store returns something in one file, and the other returns undefined. That makes no sense to me.

**Comment by marcosroot** [comment]
@timdorr
