### ISSUE TITLE
store subscribe not effect like rxjs’observerable

### ISSUE THREAD

**Issue by lgyytm** [reduxjs/redux#3496]
My situation:
 ```js
const [data, setState]= useState(currentState) // get from the store state
useEffect(()=>{
  const unsubscribe = store.subscribe(()=>{
    const globalState = store.getState();
    //shallow compare state
    //setState(state) prestate or globalState[namespace]
  });
  return unsubscribe();
},[namespace, store])
```

I can’t enter subscriber with namespace change.because globalState hasn’t changed!!
What can I do in this situation?

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.

**Comment by lgyytm** [comment]
Ok,it just makes me feel like a bug.If I can’t find the answers,could I ask again?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timdorr** [comment]
One thing of note, you're returning the result of calling unsubscribe. You should return the unsubscribe function itself: `return unsubscribe;`

**Comment by lgyytm** [comment]
yes, it's just a typewriting error~
