### ISSUE TITLE
'AnyAction' is not assignable to type

### ISSUE THREAD

**Issue by WPsArt** [reduxjs/redux#3673]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
I have the following pieces of code:
```
export type CustomAction = {
    type: "custom";
    payload: { value: true };
};
```

```
const customReducer = (state: CustomState, action: CustomAction) => {
    ...
}
```

```
const reducer = combineReducers({
    custom: customReducer
});

createStore(reducer);
```

Right now it throws the following error:
> Type 'AnyAction' is not assignable to type 'CustomState'

**What is the expected behavior?**
This worked in 4.0.4 and not in 4.0.5 anymore.

**Comment by timdorr** [comment]
You need to be defining your CustomAction as an interface, so you can extend Redux's Action type. You also need to define your reducer with the Reducer type:
```ts
const customReducer: Reducer<CustomState, CustomAction> = (state, action) => {
```
There is too much to infer otherwise. 

I'm not sure why AnyAction is trying to be assigned to CustomState, though. That sounds like a typo somewhere you meant to write CustomAction.
