### ISSUE TITLE
useSelector() does not return deep copy of state object

### ISSUE THREAD

**Issue by borakuldeep** [reduxjs/redux#3719]
### What is the current behavior?

Redux useSelector() returns shallow copy of the state. Hence, when changing(filtering) the local variable returned by useSelector, the global state is mutating. is this a bug?

### Steps to Reproduce

 https://codepen.io/kuldeep-bora/pen/vYOJdyy

### What is the expected behavior?

useSelector should return deep copy of the object (?)

### Environment Details

   "react-redux": "^7.2.0",
    "redux": "^4.0.5"

**Comment by timdorr** [comment]
This is not expected behavior of useSelector or Redux itself. You should use an immutability library, such as Inner, if you want this guarantee.

**Comment by borakuldeep** [comment]
you mean Immer I guess. Thanks

**Comment by markerikson** [comment]
Yeah, this issue is wrong on multiple levels:

- `useSelector` is in React-Redux, not Redux core
- `store.getState()` itself just returns the actual state reference, and does nothing to prevent you from mutating that state
- Therefore, both `mapState` and `useSelector` receive the actual state reference, and do not attempt to clone it in any way.
