### ISSUE TITLE
React | Redux |Reusable component rendering data of different props

### ISSUE THREAD

**Issue by Tiruvengadam85** [reduxjs/redux#3729]
I have Orderlist component which fetches data from an API via action method using redux. I am displaying fetched result from store using mapstatetoprops method. I want to make it as reusable component, so I have created brand as props in order list component, so that data should load to respective brand.
`<orderlist brand="mc"/>
<orderlist brand="vs"/>
`

Currently fetched results are showing as below

initially brand "mc"data is loading in both component after sometime brand "vs" data is loading in both component.

i want to load the data to the respective component

I am using ownprops as well
`mapStateToProps =(state, ownProps)=>{

`

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
