### ISSUE TITLE
Why is dispatch-in-a-listener allowed?

### ISSUE THREAD

**Issue by stevesan** [reduxjs/redux#3741]
There's some code that makes sure reducers don't dispatch:
https://github.com/reduxjs/redux/blob/23264c32a91414d295d32971aa2eb03b375d1327/src/createStore.ts#L248

That makes a lot of sense to me. Nested state changes are bug-prone. But why is "isDispatching" set to false there before the listeners are invoked? Shouldn't it disallow dispatches in the listener functions as well? According to FB's [FLUX talk](https://youtu.be/nYkdrAPrdcw?list=PLb0IAmt7-GS188xDYE-u1ShQmFFGbrk0v&t=737), this seems to be the right thing to do, for the same reasons.

**Comment by markerikson** [comment]
As Dan Abramov recently pointed out, [every event listener implementation has differing semantics on how subscriptions and triggering events is handled](https://twitter.com/dan_abramov/status/1241858487250038790).

I don't have an immediate answer as to why the current semantics were chosen.  The short answer is "because that's the way it is" :)  

I'd suggest digging back through some of the earlier issues for some related discussion, like these:

- #752
- #1180
- #1498

**Comment by stevesan** [comment]
Got it. Didn't realize this was a point of active discussion.

**Comment by markerikson** [comment]
Certainly not "active" in the sense of "discussion going on right now" :)  But there's been prior discussion around the topic over the years, yeah.
