### ISSUE TITLE
Redux store and connect issues

### ISSUE THREAD

**Issue by ayomirotoye** [reduxjs/redux#3782]
Could not find "store" in the context of "Connect(Component)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Component) in connect options.

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.

**Comment by ryu9827** [comment]
This issue happens to me as well. It happens when I upgrade react-redux version from v5 to v6. It works fine in v5. So I don't think it's simply an usage question.
