### ISSUE TITLE
Do Not Put Non-Serializable Values in State or Actions

### ISSUE THREAD

**Issue by MathieuPuech** [reduxjs/redux#3794]
## What docs page needs to be fixed?

- **Section**: style-guide
- **Page**: style-guide

https://redux.js.org/style-guide/style-guide#do-not-put-non-serializable-values-in-state-or-actions

## What is the problem?

In "Do Not Put Non-Serializable Values in State or Actions", there is this phrase:
> It also ensures that the UI will update as expected

## What should be changed to fix the problem?

It's not clear what UI issue you can have. Is it related to React? Redux don't do anything on UI

**Comment by markerikson** [comment]
The Style Guide isn't attempting to list specific details - it's giving you a general principle to follow.

Our docs do generally assume that you are using React, and thus React-Redux, so the advice is based on that assumption.

Specifically in this case, putting class instances into the store would usually also involve mutating those class instances, because that's what you normally do with a class.  Since React-Redux relies on shallow equality comparisons to determine if the UI needs to update, keeping the same class instance in your state would possibly result in the UI thinking that nothing had actually changed, and thus not re-rendering.

**Comment by MathieuPuech** [comment]
Ok, I didn't know this documentation was about React-Redux, I don't use this library with React and there is no issues Using Set/Map as explained in this documentation with Redux.

**Comment by markerikson** [comment]
You still shouldn't put non-serializable values in to the store even if you aren't using React, because it won't work well with the Redux DevTools.

Like I said, our docs do generally assume that you're using React-Redux, because the vast majority of Redux users are using it with React.

**Comment by MathieuPuech** [comment]
For devtools, it's just an fix that needs to be done, there is an issue to fix that: https://github.com/reduxjs/redux-devtools/issues/496

**Comment by toastal** [comment]
> it won't work well with the Redux DevTools.

This seems like a poor reason. Just because a tool doesn't work with it, doesn't mean it's not valid. Especially with `ReadonlyMap` and `ReadonlySet` you can assume these were not in fact mutated and they have properties that objects/records don't like allowing "keys" to be objects/array/etc.

**Comment by markerikson** [comment]
@toastal : since using the Redux DevTools is one of the primary reasons to choose Redux in the first place, it's an _excellent_ reason :)
