### ISSUE TITLE
Not feature requesst, suggested code refactoring: replace all && usages like action && action.type with action?.type , i.e the ?. operator

### ISSUE THREAD

**Issue by sktguha** [reduxjs/redux#3803]
### What is the new or updated feature that you are suggesting?
replace all && usages like action && action.type with action?.type , i.e the ?. operator
if it is ok to do so, then I would love to pick this up as a task
### Why should this feature be included?
I think it will improve the code understanding

**Comment by markerikson** [comment]
I'm not against the idea completely, but:

- that _is_ brand new syntax and not supported everywhere yet
- since it's new, a lot of folks aren't familiar with it either

We don't have too many places in the code or docs where we do that sort of check, so I don't see this is a particularly critical change.
