### ISSUE TITLE
Remove Google Analytics?

### ISSUE THREAD

**Issue by resynth1943** [reduxjs/redux#3815]
## What docs page needs to be fixed?

All of them.

## Remove Google Analytics

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

## What should be changed to fix the problem?

How would you feel about replaing Google Analytics?

**Comment by markerikson** [comment]
I'm not against the idea, but: GA support was already built into Docusaurus, I'm not looking to actually pay for anything here, and I don't want to have to deal with self-hosting anything either.

Tbh the "proprietary nonfree" argument doesn't matter to me at all.  I just want something that gives me reasonable stats on what pages are being hit, 404s, and external referrals, with as little effort on my part to set anything up as possible.

If someone else is willing to do the work to evaluate options, figure out how to set everything up, and I don't have to spend any meaningful time configuring things, and the results are reasonably useful, I'm open to the idea.

**Comment by markerikson** [comment]
Google Analytics is due to retire its existing implementation in a few months.  At this point I'm ready to switch over to something different, especially since I personally don't use 98% of the features in GA.  I mostly care about:

- Overall hits
- Hits per page
- External referrers and sources

The biggest issue is that the Redux docs do get considerable traffic.  `redux.js.org` had around 750K hits in the last 30 days (which includes Christmas), and 850K in November.  And... wow. React-Redux had 400K hits in November, and the RTK docs had over 1M (!!!).

Looking at Plausible's pricing, that would be at least $70/mo, and I don't want to pay that.

So, I'd really like something that is:

- Trivial to set up, configure, and integrate into Docusaurus
- Provides me at least that info
- Looks decent
- Free

I realize that's a somewhat self-entitled attitude, but hey, I'm not getting paid for this OSS gig either :)


I know that some tools like Plausible _are_ capable of being self-hosted, and I googled up a couple examples of people running Plausible on something like Fly.io with some additional work.

So: 

- Does anyone have suggestions on what tools I should consider?
- Would anyone be interested in helping set up a new analytics tool for us to use in the docs?

**Comment by orta** [comment]
FWIW, I'd also question if you need analytics at all - over time I removed analytics from every OSS docs site I worked on because they weren't providing value outside of 'number goes up' (which I could easily see from the dependency manager's site)

The only site I kept them on was the typescript site, and that was only useful during the site rewrite and the handbook 1 -> 2 transition, but I couldn't successfully argue that we should turn it off after the site/content settled and I'm willing to bet they've not been looked at in a year or so

So, I'd ask yourself what you are tracking for and if it could be done a better way, or skipped entirely before also thinking about switching providers.

**Comment by markerikson** [comment]
@orta : I found the stats extremely valuable while rewriting the tutorials to see what topics I ought to hit, and given that I still have a mile-long list of docs pages I _want_ to redo, I think this info would still be useful going forward.

**Comment by aloukissas** [comment]
Perhaps something bare-bones like [this](https://notes.normally.com/cookieless-unique-visitor-counts/)?

**Comment by phryneas** [comment]
We really don't want to roll our own solution. We already have a lot on our hands.

**Comment by markerikson** [comment]
Finally done by switching to Umami

**Comment by ryota-murakami** [comment]
@markerikson Umami is so sweet!
Also Umami seems to be a good role model for how to combine OSS SaaS with monetization.

Might be we could close it? https://github.com/reduxjs/redux/pull/4465
