### ISSUE TITLE
Question: Redux update store when React Native app is in the background

### ISSUE THREAD

**Issue by danwhite-ipc** [reduxjs/redux#3822]
Initially I apologies for not follow proper conduct but I have exhausted all other avenues to find an answer. I have an issue where when the app is in the background or transitioning to the background my updates to the redux store do not happen. This is happening at the moment due to events triggered by React-Native-CallKeep when the app is in the background in which I need to update my store on the status of calls. Any pointers in the general direction of an answer or a work around would be greatly appreciated.

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.

**Comment by danwhite-ipc** [comment]
I have tried Stack Overflow and Reactiflux I've not been able to find an answer. Was hoping for just a point in the right direction
