### ISSUE TITLE
How do I ignore subscribing to some of the props in my redux store

### ISSUE THREAD

**Issue by jahnavi-jh** [reduxjs/redux#3835]
Hi, I have my store with combine reducers.. My store has many props .. but i need to listen to change in specific props 
I am not finding any way.. Can you please help

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
