### ISSUE TITLE
Fixing create store docs tutorial

### ISSUE THREAD

**Issue by herolindl** [reduxjs/redux#3884]
## What docs page needs to be fixed?

- **Section**: Store
- **Page**: redux/docs/tutorials/essentials/part-1-overview-concepts.md

## What is the problem?

The overview concept tutorial follows a pure redux explanation from the beginning only when creating store it uses

```
import { configureStore } from '@reduxjs/toolkit'

const store = configureStore({ reducer: counterReducer })
```

which creates confusion for people not familiar with redux. The tutorial should follow "a single source of truth".

## What should be changed to fix the problem?

```
import { createStore } from 'redux'

const store = createStore(todos, ['Use Redux'])
```

**Comment by timdorr** [comment]
Nope, we specifically built this guide around using Redux Toolkit. It's mentioned in the "What you learned" section:

> Redux Toolkit is the recommended way to write Redux logic

**Comment by Microserf** [comment]
I just stumbled on the same problem. Now that you point it out @timdorr, I can see that the tutorial was written with Redux-Toolkit in mind, as you say, but I wonder if there might be a way to highlight this a little more?

Perhaps it would help to explicitly state the `npm install` commands at the top of the page, to make the requirements copy-pastable?

**Comment by markerikson** [comment]
Part of the issue here is that the tutorial specifically gives you a pre-configured repository that already has Redux Toolkit added to it (which is in turn based off of the Redux+JS template for Create-React-App, which _also_ has RTK already configured):

https://redux.js.org/tutorials/essentials/part-3-data-flow#project-setup

 So, in both those cases there isn't even anything to install.  The tutorial _does_ have a "Detailed Explanation" section that explains how to add Redux to an existing project.

Given that structure, I'm not immediately sure where an NPM installation command would fit into page 1, but I"m open to suggestions.
