### ISSUE TITLE
Not updating after a dispaching

### ISSUE THREAD

**Issue by davidarnaub7** [reduxjs/redux#3913]
I've integrated Realm with Redux on my app. Each time I do an action I want to register in the database I call to an action with dispatch, save on Realm and return the new information to the reducer. It works correctly. I have already subscripted to the changes on the screen I want to the data has been update. 

So, the problem is the next. I'm in a secondary view where I do a booking. In this view, the state updates correctly and the view changes too. But in the main view (where I've donde the subscription) the data doesn't update. The subscription callback is launched, I know it because I put a console.log and the redux store has the correct info, but when I set the new date state, the view doesn't re-render although the state has the correct data too.  I don't know why happens this. 

 const [bookings, setBookings] = useState(store.getState().booking.bookings);
  const unsubscribe = store.subscribe(() => {
    console.log('update');
    setBookings(store.getState().booking.bookings);
  });

I've done everything, with a UseEffect hook, without it.

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
