### ISSUE TITLE
Actions - state updating for different actions files

### ISSUE THREAD

**Issue by Sumedh-ravi1604** [reduxjs/redux#3915]
Consider Action1.ACTION_NAME and Action2.ACTION_NAME, whenever their are 2 actions and 2 different reducers for each action, and i want to update by dispatching to (Action2.ACTION_NAME) the dispatch is updating both the actions  (Action1.ACTION_NAME and Action2.ACTION_NAME) and the state gets changed.

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
