### ISSUE TITLE
 ReferenceError: Can't find variable: ObjectId When use createStore

### ISSUE THREAD

**Issue by mandeptrai123** [reduxjs/redux#3970]
my package.json :
"react-redux": "^7.2.2",
    "redux": "^4.0.5",
 "react-native": "^0.63.4"

when use createStore in my store.js .
I catch 1 bug .
Can't find variable: ObjectId .
i was upgrade react-native to 0.63.4 .

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use [our Discussions page](https://github.com/reduxjs/redux/discussions?discussions_q=category%3AHelp), [Stack Overflow](https://stackoverflow.com/questions/tagged/redux), or [Reactiflux](https://www.reactiflux.com/) where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
