### ISSUE TITLE
Simplification request for middleware documentation

### ISSUE THREAD

**Issue by borasemiz** [reduxjs/redux#4016]
## What docs page needs to be fixed?

- **Section**: Understanding Redux > History and Design
- **Page**: Middleware

## What is the problem?

This page contains quite a bit of unnecessary reading. Even for a person who has only a basic knowledge of redux, reading these sections are just unnecessary:

- Attempt 1: Logging Manually
- Attempt 2: Wrapping Dispatch
- Attempt 3: Monkeypatching Dispatch
- Problem: Crash Reporting
- Attempt 4: Hiding Monkeypatching
- Attempt 5: Removing Monkeypatching
- Attempt 6: Naïvely Applying the Middleware

The **Final Approach** section only would be enough to give the gist of the solution. I personally skipped all the sections above.

## What should be changed to fix the problem?

Delete the sections that wrote above.

**Comment by markerikson** [comment]
The point of the page _is_ to explain why middleware work the way they do.

This page actually used to be part of the old "Advanced" tutorial sequence.  In that context, yes, the explanations were unnecessary.  Because of that, when I replaced the old "Basics/Advanced" tutorial sequence with the new ["Redux Fundamentals" tutorial](https://redux.js.org/tutorials/fundamentals/part-1-overview), I specifically wrote all-new sections on [how to _use_ middleware by adding them to the Redux store](https://redux.js.org/tutorials/fundamentals/part-4-store#middleware), and [how/why to use middleware for side effects](https://redux.js.org/tutorials/fundamentals/part-6-async-logic#redux-middleware-and-side-effects).

However, this content still provides a good explanation for why we ended up with the middleware definition syntax that we have now.  So, I moved that existing page over to the "Understanding Redux" section, because it fits that better.

So, no, no plans to remove content from the page - it's explaining what it's supposed to given its location in the docs.
