### ISSUE TITLE
crossSliceReducer example is buggy-maybe

### ISSUE THREAD

**Issue by lazybean** [reduxjs/redux#4070]
## What docs page needs to be fixed?
https://redux.js.org/recipes/structuring-reducers/beyond-combinereducers

- **Section**:  recipes
- **Page**: structuring-reducers/beyond-combinereducers

## What is the problem?
I believe the example of the third approach with the `crossSliceReducer` has a bug.
The `sliceReducerB` will be executed twice.

Here is the example from the doc with an added inline comment pointing the problem.
```
const combinedReducer = combineReducers({
  a: sliceReducerA,
  b: sliceReducerB
})

function crossSliceReducer(state, action) {
  switch (action.type) {
    case 'SOME_SPECIAL_ACTION': {
      return {
        // specifically pass state.b as an additional argument
        a: handleSpecialCaseForA(state.a, action, state.b),
        b: sliceReducerB(state.b, action)  //  ⚠🐛 state.b has already been updated by sliceReducerB in the combined reducer.
      }
    }
    default:
      return state
  }
}

function rootReducer(state, action) {
  const intermediateState = combinedReducer(state, action)
  const finalState = crossSliceReducer(intermediateState, action)
  return finalState
}
```

If we take the following simple reducer 
```
function sliceReducerB(stateB = {counter: 0}, _action) {
 return {counter: counter+1}
}
```

We will have the following state (only showing slice B) :
```
function rootReducer(state, action) {
  const intermediateState = combinedReducer(state, action)
  // intermediateState is {b: counter: 1,  }
  const finalState = crossSliceReducer(intermediateState, action)
  // finalState is {b: counter: 2} 😿
  return finalState
}

```

## What should be changed to fix the problem?

The crossSliceReducer should only update a.

**Comment by markerikson** [comment]
Appreciate the concern, but this is _mostly_ intentional.

A couple things here:

- First, it's a made-up example. The actual reducer logic _could_ be anything we want it to be.
- Second, in this _specific_ example, the assumption is that `sliceReducerB` probably knows nothing about `SOME_SPECIAL_ACTION` - this `crossSliceReducer` is most likely the only function that actually cares about that.  So, if that action _is_ dispatched, slice B probably won't have updated because it doesn't care about this action.
 
Given all that, I'm inclined to leave the example as-is.  

Please let us know if you do have any other questions or concerns about the docs examples!

**Comment by lazybean** [comment]
Thank you for clarifying the intention of the example.
