### ISSUE TITLE
Proposition: add back and foreground states as additional state layers

### ISSUE THREAD

**Issue by AdamBraun** [reduxjs/redux#4091]
Allow layered state.
Currently, Redux allows for one state to exist. It works great and is easy to reason about as there is but one *single* source of truth.
However, it does not allow for actions across the system's components. There are cases in which I would want each component to continue its regular lifecycle in the background, while an event that requires the user's attention overshadows it.

For example: Zen mode (do not disturb), notifications (toasts, modals) etc..

The component in charge of, say, the Zen mode, has no business changing other component's lifecycle or state. However, it needs to shadow it for its own functionality.

Today, I have two alternatives:
- Either the Zen mode's reducers will need to micro manage other component's lifecycle and state, or
- the other components will need to implement relevant actions and reducers for them to be reactive to outside changes.

My proposition:
Allow for extra two layers of state to be managed. Background and foreground.
logically, it should look something like
```
updatedState = { ...backgroundState, ...newState, ...foregroundState };
```
and
```
const { background, state, foreGround } = getState();
```

This approach will allow components to do cross system actions without interfering with other component's lifecycle or polluting their reducers.

Pros:
- Does not change the current use of redux
- A greater level of flexibility for cross component behaviour

Cons:
- Will add a level of complexity to state management
- Harder to reason about

**Comment by markerikson** [comment]
This doesn't seem like something we would want to pursue implementing, for a few reasons:

- The Redux core is effectively "done", and we have no plans to add any further real features to it
- There are already multiple implementations of "undo/redo" functionality in the ecosystem
- This seems very specific to the applications you're working on
- It's likely something that could be implemented as a "store enhancer" rather than requiring modifications to the core store logic
