### ISSUE TITLE
[Docs] Add typescript and @reduxjs/toolkit examples in recipes

### ISSUE THREAD

**Issue by vinay-deshmukh** [reduxjs/redux#4115]
## What docs page needs to be fixed?

Need to add typescript and @reduxjs/toolkit examples next to plain javascript for the recipes page.

https://redux.js.org/recipes/structuring-reducers/reusing-reducer-logic

## What is the problem?

This page is a "advanced" use case, and in one of my projects, I had need of this concept, but since there weren't examples with typescript _and_ toolkit, I wasn't sure how to implement this in  a way that doesn't become too complicated. Since we are interpolating actions as `INCREMENT_${counterName}`, so you need to create action creators for it. 

In this case, the "higher order reducer" needs to return the action creators as well. I think this might be too complicated hence, it would be better if docs mention the recipe with typescript and toolkit support(as toolkit encourages usage of `createAction` over literal strings.

## What should be changed to fix the problem?

Add examples with typescript and redux toolkit to show usages with "typed" language, and also, in the example with `createCounterWithNamedType`, show how to use `createAction` and `createReducer`; and how to use them both to create a higher order reducer.

Similar changes could be done for other pages as well, since interpolating an action string is "simple", but when you add action creators, that needs some

**Comment by timdorr** [comment]
If you're using RTK, you should be consulting the RTK docs first: https://redux-toolkit.js.org/usage/usage-with-typescript

**Comment by markerikson** [comment]
FWIW, the principles shown in that page apply regardless of whether you're using plain Redux, RTK, JS, or TS.

We do have an example in the RTK "TS Usage Guide" page Tim linked that happens to show this pattern, specifically because using `createSlice` with TS in this case can be tricky:

https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice

You can see, though, that it's the exact same pattern in principle.  Pass in some parameters like a `name` or something, generate logic using that as a distinguishing factor, return the generated pieces.
