### ISSUE TITLE
CodeSandbox from Redux Essentials, Part 5 documentation not functional

### ISSUE THREAD

**Issue by jasonsturges** [reduxjs/redux#4212]
## What docs page needs to be fixed?

Redux Essentials, Part 5: Async Logic and Data Fetching
- Tutorials -> Redux Essentials -> Async Logic and Data Fetching -> What You've Learned
- WebPage: https://redux.js.org/tutorials/essentials/part-5-async-logic#what-youve-learned
- CodeSandbox: https://codesandbox.io/s/github/reduxjs/redux-essentials-example-app/tree/checkpoint-3-postRequests/

## What is the problem?

CodeSandbox is not functional:

> Unexpected token < in JSON at position 0

![image](https://user-images.githubusercontent.com/1213591/140458266-1da1f18c-014a-42bf-bdb7-6484fc24559a.png)

## What should be changed to fix the problem?

Presumably the API faker for authors is not returning expected result?

It might be a race condition, as once I start editing the sandbox the issue is resolved during live update.

**Comment by markerikson** [comment]
Yeah, this may be due to an issue we'd noted with the startup logic for the `msw` API mocking lib. The index file should really be doing `await worker.start()`, but instead it's just doing `worker.start()` and continuing.  I haven't had a chance to go back and rewrite the repo's history to make that change.

**Comment by markerikson** [comment]
Should be fixed now!
