### ISSUE TITLE
Code structure for a store with normalized data

### ISSUE THREAD

**Issue by markoj3s** [reduxjs/redux#4261]
## What docs page needs to be fixed?
https://redux.js.org/tutorials/essentials/part-6-performance-normalization#normalized-state-structure

## What is the problem?
Based on the documentation on how to normalize state, it seems that it is keeping thunks inside the related slice module.
However, when normalizing state, thunks would usually return multiple entities and trigger several slices/reducers which would then update their part of the state. By doing so, it is quite quick and easy to fall in some circular dependencies between some slices. So I thought that when normalizing state, thunks should typically (and not only for some minor exceptions) end up in a dedicated sliceXXXThunk module from where all slices could import safely the thunks and build the actions around them. (which would step away from the duck/slice pattern but would be more solid)

## What should be changed to fix the problem?
The documentation is great but, it would be even greater if it could be explained how to cleanly implement state normalization which is, I think, a quite crucial part, and this without ending up in sliceA importing thunks from sliceB and sliceB importing thunks from sliceA, while remaining in the spirit of redux's slice "standard".
I know that redux is not supposed to be opinionated but my making slices a "standard", I think it is important to help developers to use those slices in a solid way.

**Comment by markerikson** [comment]
The "Normalizing State Shape" page is intended to be a high-level explanation of the concept of normalized state.  It's not a direct "here's the exact code you should write" document.

Additionally, the focus in that page is about the _state structure_, rather than how the rest of your code is organized.

I'm not sure I follow the rest of your train of thought here. Why would normalizing state result in "thunks that return multiple entities"?  Why would that lead to circular dependencies?

That kind of sounds like you're writing thunks that make a request and then specifically dispatch many actions in sequence for "item type A loaded", "item type B loaded", "item type C loaded", etc. If that's what you're doing, please don't :)  We specifically recommend [modeling actions as "events"](https://redux.js.org/style-guide/style-guide#model-actions-as-events-not-setters), [letting many reducers handle the same action](https://redux.js.org/style-guide/style-guide#allow-many-reducers-to-respond-to-the-same-action), and [_not_ dispatching multiple actions in a row](https://redux.js.org/style-guide/style-guide#avoid-dispatching-many-actions-sequentially).

Instead, dispatch _one_ action that says "fetched some data from the server", and let all the relevant reducers process that action as appropriate.

**Comment by markoj3s** [comment]
Hi @markerikson 

Thanks for your quick reply!

Yes I understood that it was only a high-level explanation, and was actually talking about the example mentioned in that page.
I had an overall look at the documentation to get a grasp about how to structure my code both in a solid way "while remaining in the redux spirit", and tried to guess the best practices by looking at the examples and the best practices section. 

The information I extracted were:
- slices being the modern and standard
- slices are encouraging duck pattern
- in the examples, thunks being imported from slices

Based on that information, I naturally started using slices and organizing the code into ducks.

Then I tried to battle against duplicated data in the store by normalizing it (using createEntityAdaptater and normalizr).

Finally, to answer your question at the same time, I've read in the best practices section that actions should be treated as events to avoid dispatching multiple actions in a row for a specific event. So this is what I've been doing but when it comes to thunks with normalized data, here is a concrete example of my actual problem:

Lets's say I have a usersSlice and a postsSlice, both normalized.
Then, I trigger my `fetchPosts` action defined inside postsSlice to fetch a list of post with the author nested/included and one post object would look like below.
```
{
  "id": "123",
  "author": {
    "id": "1",
    "name": "Marko"
  },
  "title": "My awesome post"
}
```
This object would get normalized and give something like
```{
  result: "123",
  entities: {
    "posts": {
      "123": {
        id: "123",
        author: "1",
        title: "My awesome post"
      }
    },
    "users": {
      "1": { "id": "1", "name": "Marko" },
    }
  }
}
```
I will then pass `fetchPosts.fullfiled` to postsSlice to extract entities.posts and update the store with the posts data, and also pass it to usersSlice to extract entities.users and update the store with that data as well.

Now here comes the problem: let's say we have a userPage and we want to trigger `fetchUserById` action defined inside usersSlice to retrieve the data of a user and also that user's latest 5 posts, the api response would be:

```
{
  "id": "1",
  "name": "Marko",
  "latestPosts": [
    {
       "id": "123",
       "title": "My awesome post123",
    },
    {
       "id": "456",
       "title": "My awesome post456",
    }
  ],
}
```
Here again after normalizing the response, I would have entities.users and entities.posts, and would need to import usersSlice/fetchPosts from postsSlice to update the post related datas.

Eventually, postsSlice will import usersSlice/fetchUserById and usersSlice will import postsSlice/fetchPosts, resulting in a circular dependency.

So I thought that either: I misunderstood the concept of normalizing the data or normalizing data does not fit with slice/duck pattern.

I really feel that the slice/duck pattern is a clean way of writing redux code, so that's why I am doing my best to do it well and raised that concern :)

**Comment by markerikson** [comment]
A few different thoughts here.

One is that [RTK 1.7.0 fixed the problem with circular dependencies breaking `createSlice`](https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.0).  They're still probably not a _good_ thing, but they won't cause your slice to break during initialization.

Second, **the issue is not the slices or the normalization itself, but rather that you are specifically referencing the thunks for those data types and their `fulfilled` actions across the two slices**.  There's multiple ways to break those cycles, like moving the thunks themselves out to separate files (as you originally noted), or falling back to hand-writing the relevant action types strings when you call `builder.addCase()`.

Another approach could be using `builder.addMatcher()` to match not on specific actions, but rather on the existing of something like `action.payload.entities.posts` and then process any action that has that data field inside.

**Comment by markoj3s** [comment]
Hi @markerikson 

Sorry for the late reply and thanks a lot for your insight!

Good to know about RTK 1.7.0 fix :)

Also, yes, that's right, my issue is not _directly_ related to slices/normalization and more related to the way I am implementing it.

Thanks a lot for sharing those solutions and I particularly like the **addMatcher** approach (which is an api I overlooked and should have not) as it will allow me to both solve the circular dependency issue and also the other concern I had, which is omitting to pass an action to some slices,
e.g. actionA returns entities B and C, I import actionA from sliceB to retrieve entityB but forget to import that same action from sliceC to retrieve entity C

I am now clear on how to cleanly implement the normalization of my store, thank you for your time!

Also, by reading redux's documentation, I came across another concern related to a totally different topic (useSelector and stale props), but I guess I should ask about it in the discord to avoid polluting this topic and the issues section?

**Comment by markerikson** [comment]
Reactiflux would be a good place to ask, yeah.

There's some good resources on this topic in the hooks API docs:

https://react-redux.js.org/api/hooks#stale-props-and-zombie-children

It's worth noting that we've had far more people complain that "oh no the docs say this is a thing that _could_ happen!" then have ever complained about it _actually happening :)

**Comment by markoj3s** [comment]
Ok got it!
Yes I actually first read the https://redux.js.org/tutorials/fundamentals/part-5-ui-react section where it was mentioning that passing the itemId instead of the item itself to a child component would improve the performance, with the example `const todo = useSelector(state => selectTodoById(state, id))` (id coming from the props) then came across the source you just mentioned, which was mentioning _Don't rely on props in your selector function for extracting data_, then got lost :thinking:
Let me continue about this in the Reactiflux discord :yum:
