### ISSUE TITLE
use 'it' instead of 'test'

### ISSUE THREAD

**Issue by ronytesler** [reduxjs/redux#4264]
## What docs page needs to be fixed?

- **Section**: Reducers​
- **Page**: https://redux.js.org/usage/writing-tests

## What is the problem?
When using sentences like "should handle a todo being added to an empty list", shouldn't we use the 'it' function instead of 'test'?
Like explained here: https://stackoverflow.com/questions/45778192/what-is-the-difference-between-it-and-test-in-jest

## What should be changed to fix the problem?
change 'test' to 'it', in the code example.

**Comment by msutkowski** [comment]
This is a preference thing that doesn't add any clarity to these docs. Some teams adopt `it` instead of `test`, but for the sake of examples, `test` is a bit more explicit than requiring someone to know what jest's aliases are. If this really bothers you, you could open a PR for these changes, but IMO it's not necessary whatsoever.

**Comment by ronytesler** [comment]
For me it doesn't matter, just for who uses the docs, not to create a confusion with the stackoverflow answer. I understand that 'test' is clearer, so maybe it's better to change the description that's passed to the test function. Anyway, whatever you decide of course : ).
