### ISSUE TITLE
Bullshit

### ISSUE THREAD

**Issue by happysmile12321** [reduxjs/redux#4360]
you just a pure thing,so complex,bullshit!!!

**Comment by phryneas** [comment]
Hello HappySmile12321,

reading your very detailed question, I would assume that you are following an outdated Redux tutorial. Please be aware that modern Redux does not use `switch..case` reducers, ACTION_TYPE constants, hand-written action creators, immutable update logic in reducers, `connect`/`mapStateToProps` or complex `createStore` store setup - since 2019. Unfortunately, many tutorials out there have not updated since and unfortunately some (not very trustworthy) authors are still putting up outdated tutorials to this day.

I would highly recommend you stop following the sources you are following right now and following [the official "Redux Essentials"](https://redux.js.org/tutorials/essentials/part-1-overview-concepts) tutorial instead, which teaches you modern Redux, which is much less error-prone and about 1/4 of the code. It still has some complexity, since there are just a lot of things you can do with Redux, but it has a lot less moving parts.

I wish you a happy day with lots of happy smiles, HappySmile12321.

PS: I would recommend you to take care of your number of exclamation marks since [according to Terry Pratchett](https://wiki.lspace.org/Multiple_exclamation_marks), "a person's sanity is inversely proportional to the number of exclamation marks they use".
