### ISSUE TITLE
Consider removing Internet Explorer support

### ISSUE THREAD

**Issue by nickmccurdy** [reduxjs/redux#4368]
Its official support is ending, so we could probably save a bit on Babel resource usage. This would technically be a breaking change though, not sure how we'd want to deal with that.

**Comment by Methuselah96** [comment]
Would love to finally get a v5 out there with some [cleaned up types](https://github.com/reduxjs/redux/issues/4129). This could be a good ~excuse~ reason to do so.

**Comment by markerikson** [comment]
@nickmccurdy There's barely anything IE relevant in this codebase :)  Closest I can see looking at a build artifact is:

```js
  for (var _len = arguments.length, funcs = new Array(_len), _key = 0; _key < _len; _key++) {
    funcs[_key] = arguments[_key];
  }
```

I agree it'd be nice to put out v5 at some point. My biggest questions are still around ecosystem compat with the types.

**Comment by nickmccurdy** [comment]
I'm mostly referring to how the Babel/browserslist config explicitly support IE in the build. Is that explicitly tested though?

**Comment by markerikson** [comment]
Yeah, I'm just saying that Redux's code is so minimal, and it's so FP-oriented, that there's almost nothing in the current code that would matter for IE beyond a couple bits of ES6 syntax.  So, sure, we ought to remove that setting in the next major.  There just won't be much of a size difference because it's a small lib and there's only a couple tiny bits of syntax that would be affected.

**Comment by nickmccurdy** [comment]
That's fair. Would a draft PR to test dropping it help, or would you rather wait until the types are more ready?

**Comment by markerikson** [comment]
Dead in the 5.0 alphas!
