### ISSUE TITLE
Mix two reducer in index.js redux

### ISSUE THREAD

**Issue by Mohammad-HGH** [reduxjs/redux#4371]
Hi, i have problem with redux and read documentation but since now i couldn't understand what should  i do in my case.
i had an action and reducer for auth and i want add another action and reducer to doing and store smth else.
but i had this error:
Uncaught Error: The slice reducer for key "auth" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined. 
but in auth i hadn't function to return "undefine"

![Screenshot from 2022-06-14 19-31-17](https://user-images.githubusercontent.com/88213502/173612800-28053c4f-c362-49e1-b90b-1c4c764973ae.png)
![Screenshot from 2022-06-14 19-31-29](https://user-images.githubusercontent.com/88213502/173612830-d0c0565a-bd67-4262-909d-07229153c560.png)
![Screenshot from 2022-06-14 19-31-36](https://user-images.githubusercontent.com/88213502/173612851-368a56e5-533d-4d84-ab40-cea6fb39726d.png)
![Screenshot from 2022-06-14 19-31-47](https://user-images.githubusercontent.com/88213502/173612883-96f5d2ba-705c-4afe-ae3e-435abd1c399e.png)
![Screenshot from 2022-06-14 19-31-53](https://user-images.githubusercontent.com/88213502/173612901-9b465dd8-774f-4113-876e-34a85bd40d42.png)

**Comment by markerikson** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. 

That said, the real issue here is that you haven't provided an initial value for `state` in the auth reducer.  So, yes, it _is_ `undefined` by default.

Also: the style of Redux code you're writing there is very outdated.  Please switch to using our official Redux Toolkit package, which is much simpler and easier to use:

https://redux.js.org/tutorials/index
