### ISSUE TITLE
Journey to Redux Middleware: Monkey Patching not in correct way

### ISSUE THREAD

**Issue by khobaib222** [reduxjs/redux#4424]
## What docs page needs to be fixed?
- **Page**: https://redux.js.org/understanding/history-and-design/middleware
- **Section**: https://redux.js.org/understanding/history-and-design/middleware#problem-crash-reporting

## What is the problem?
In this section, is this piece of code even a solution? Here we are overriding the ```dispatch``` in both the functions, which means the function which is executed later somewhere in the code will not have the actual store's ```dispatch``` method in ```next```, it would be the one which was assigned from one of the functions which executed first.

```function patchStoreToAddLogging(store) {
  const next = store.dispatch
  store.dispatch = function dispatchAndLog(action) {
    console.log('dispatching', action)
    let result = next(action)
    console.log('next state', store.getState())
    return result
  }
}

function patchStoreToAddCrashReporting(store) {
  const next = store.dispatch
  store.dispatch = function dispatchAndReportErrors(action) {
    try {
      return next(action)
    } catch (err) {
      console.error('Caught an exception!', err)
      Raven.captureException(err, {
        extra: {
          action,
          state: store.getState()
        }
      })
      throw err
    }
  }
}
```
## What should be changed to fix the problem?
This solution should not be included in the doc.

**Comment by markerikson** [comment]
Dan wrote that particular page way back in 2015, so it's been around for a while.

If you look at it, it's _not_ using `applyMiddleware`.  It's grabbing the value of `store.dispatch`, _at the time this override function is called_.  

At the end of the section, it shows calling each override function separately:

```ts
patchStoreToAddLogging(store)
patchStoreToAddCrashReporting(store)
```

So, when `patchStoreToAddLogging` runs, `const next = store.dispatch` points to the _original_ `store.dispatch`.  When `patchStoreToAddCrashReporting` runs, it points to the first wrapper from `patchStoreToAddLogging`.

That seems like legal and correct code to me, and this _is_ ultimately how middleware end up working (just with `applyMiddleware` doing the overriding).

But also this is a conceptual explanatory that works up to "_why_ do middleware work this way?", rather than "this is how you _should_ do things".
