### ISSUE TITLE
Middleware `action` is typed as `any`

### ISSUE THREAD

**Issue by ethanneff** [reduxjs/redux#4518]
The documentation is missing typing on  `action`.  https://redux.js.org/usage/usage-with-typescript#type-checking-middleware

```ts
export type AppStore = typeof store;
export type AppState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
export type AppMiddleware = Middleware<void, AppState, AppDispatch>;

export const loggerMiddleware: AppMiddleware =
  (storeApi) => (next) => (action) => {
    const state = storeApi.getState();

    console.log(action.type, state); // Unsafe member access .type on an `any` value.

    return next(action); // Unsafe return of an `any` typed value.
  };
```

**Comment by markerikson** [comment]
Yep. Type `action` as `unknown` here in the middleware.

Per that article, we really don't find it useful to limit what _can_ be passed into `dispatch` at the TS level.

**Comment by guillaumebrunerie** [comment]
I would also very much like it to default to `unknown`, which is (in my opinion) the correct way to say that it can be anything at all.
Generally speaking, I would love that all instances of `any` be replaced by `unknown`. Having bugs that would have been prevented by Typescript just because Redux silently introduced some `any` type somewhere is one of the few places where I find the typing suboptimal. For instance the `Reducer` type defaults with `any`, and there are various other places where the `AnyAction` type is used.

**Comment by Methuselah96** [comment]
I am also interested in defaulting those to `unknown` for v5 and have poked at that a little bit. It should be possible to make state default to `unknown`, but actions are a bit more tricky since they need to be covariant in some places and contravariant in other places.

**Comment by Methuselah96** [comment]
Although after discussing it some more, I think they're always contravariant, but it will still take more work to avoid `AnyAction` for the default type.

**Comment by guillaumebrunerie** [comment]
I experimented a bit with replacing `any` with `unknown` in `AnyAction` and middlewares, and managed to do it with only fairly minimal changes (I only tested with the `test:types` script, not on any real codebase), see here: https://github.com/guillaumebrunerie/redux/commit/435fd41b1cab4c13a7c39f4971d328319abb49cb
The two other changes I needed to do are
- `ReducersMapObjects`, `ActionFromReducersMapObjects` and the third overload of `combineReducers` take an additional `S` type argument. I am not quite sure why this is needed.
- `Action` has been changed from an interface to a type. I don’t know if that would be a breaking change, and I’m also not sure why this is needed, but at least it works.

When it comes to the tests, it broke two tests:
- one was doing `state + action.count` without even checking that `action.count` is a number. It used to work because `action.count` was typed as `any`, but it doesn’t work anymore when it is `unknown` (as expected)
- another one also required changing an interface to a type, otherwise some type guard behaves differently somehow.

**Comment by EskiMojo14** [comment]
yeah, you're right - i was running into a bunch of headaches with Action not being assignable to UnknownAction, but changing Action to a type fixes it

[very odd](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIILMA9iAkuaeJAHgBVkBeZAVxAGsQsB3EAPmQG8AoZX5MAJ4AHCAC5kpLgF8uXQSLQZsIUsIhlKNeoxbsq3PvzXjJMrqEixEKVCAHpMOZBAAekEABMAzosd4CViRwduwGfADarmBQcAAKUFhCXuJe0aAA5gC64sEC0rIWhNbIAKrazCAOys5uEJ4+VTj4lkQoYbyRbjHxicnIqVAZ2VoMFflcCDipNSIYqF5ewOkgcABGADYoVGQANKwAFABucOsmAJSU7MfrspMg04h+zUVI4o3+LcX6PHzyYsgAcgB+VcszA80WyzWm2ItnsShwB0eymegQgZ1kAHpMcgmAALAT8PFYLigiBzBZLFYbdRlUYsd5IhEfF7o2QTKZgZDInCqERvZl8racH68P7iIHjMkUyHUmFwxn7HkqNQY0kuMEQqnQ2nlBnMpl+IVqoA)
